### ISSUE TITLE
Injected Fields in Beans created with MethodPojoFactory are not resolved

### ISSUE THREAD

**Issue by rnedkov** [nill14/utils#1]
Example:

```java
Module{
@Provides
IFileService providesFileService(){}
}

FileService implements IFileService{
@Inject IUserService userService;
}
```

FileService.userService would not be resovled (MethodPojoFactory.getDescriptior() returns PojoInjectionDescriptor for IFileService.class -> fields is empty).

It could be fixed in MethodPojoFactory.newInstance():

```java
@Override
public T newInstance(IPropertyResolver resolver, ICallerContext context) {
  T instance = injectMethod(resolver, context);
  this.beanDescription = new PojoInjectionDescriptor<>(TypeToken.of(instance.getClass()));
  if (instance != null) {
    resolver.initializeBean(getDescriptor(), instance, context);
  }
 return instance;
}
```

**Comment by nill14** [comment]
Thanks Radi, I see the problem.
We take the descriptor of the declared (super)type, not of the real instance type. The same problem applies to ProviderTypePojoFactory, I think. 
Another part of the problem would be to make sure the instance is not initialized accidentally twice. I would like to have a test and fix it including the initialization problem.
Also please note that injectMethod() could return not only FileService but also FileService2, for instance. Therefore, the PojoInjectionDescriptor must be a local variable here, I think.

**Comment by nill14** [comment]
The problem was resolved in https://github.com/nill14/utils/commit/11f7e786d647525ad4efbb8ca8cbac38e029cc20
